function S1001S1BLG = importasc(filename, dataLines)
%IMPORTFILE Import data from a text file
%  S1001S1BLG = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  S1001S1BLG = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  S1001S1BLG = importfile("C:\Users\hkgri\Documents\MATLAB\GazeBaseConversionWorkflow\Subject_1001\S1\S1_Balura_Game\S_1001_S1_BLG.asc", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Dec-2020 19:08:03

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "n", "X_Position_Degree_Right_Eye", "Y_Position_Degree_Right_Eye", "Distance_From_RightEye", "Validity_Right_Eye", "Pupil_Diameter_RightEye", "x", "y", "Distance_From_LeftEye", "val", "dP", "xT", "yT"];
opts.SelectedVariableNames = ["n", "X_Position_Degree_Right_Eye", "Y_Position_Degree_Right_Eye", "Distance_From_RightEye", "Validity_Right_Eye", "Pupil_Diameter_RightEye", "x", "y", "Distance_From_LeftEye", "val", "dP", "xT", "yT"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
S1001S1BLG = readtable(filename, opts);

end